package dev.chronovault.core.domain;

public enum OperationStage {
    PLANNED, PROTECTING, PROTECTED, RESTORING, VERIFYING,
    COMMITTING, COMPLETED, FAILED, ROLLING_BACK, ROLLED_BACK,
    CANCELLED, CREATING_CHECKPOINT, SCANNING, HEALTHY, BROKEN,
    UNKNOWN
}