"use strict";

// Build step: produces a deterministic bundle so health checks can verify output.
const fs = require("fs");
const path = require("path");

const src = fs.readFileSync(path.join(__dirname, "..", "src", "index.js"), "utf8");
const banner = "/* chrono-node-demo bundle v1.0.0 */\n";
fs.mkdirSync(path.join(__dirname, "..", "dist"), { recursive: true });
fs.writeFileSync(path.join(__dirname, "..", "dist", "bundle.js"),
  banner + "\"use strict\";\n// generated by chronovault demo build\n" + src);
console.log("bundled dist/bundle.js");